/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_suntec_merbok_jni_vr_UIVrMessageJNI_VrTriggerObserver */

#ifndef _Included_net_suntec_merbok_jni_vr_UIVrMessageJNI_VrTriggerObserver
#define _Included_net_suntec_merbok_jni_vr_UIVrMessageJNI_VrTriggerObserver
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
