/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vr_suntec_net_vrapp_vrService_vrEngine_BaiduPocJNI */

#ifndef _Included_vr_suntec_net_vrapp_vrService_vrEngine_BaiduPocJNI
#define _Included_vr_suntec_net_vrapp_vrService_vrEngine_BaiduPocJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vr_suntec_net_vrapp_vrService_vrEngine_BaiduPocJNI
 * Method:    SendMessage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vr_suntec_net_vrapp_vrService_vrEngine_BaiduPocJNI_SendMessage
  (JNIEnv *, jclass, jstring);

/*
 * Class:     vr_suntec_net_vrapp_vrService_vrEngine_BaiduPocJNI
 * Method:    StopDiag
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vr_suntec_net_vrapp_vrService_vrEngine_BaiduPocJNI_StopDiag
  (JNIEnv *, jclass);

/*
 * Class:     vr_suntec_net_vrapp_vrService_vrEngine_BaiduPocJNI
 * Method:    StartDiag
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vr_suntec_net_vrapp_vrService_vrEngine_BaiduPocJNI_StartDiag
  (JNIEnv *, jclass, jstring);

/*
 * Class:     vr_suntec_net_vrapp_vrService_vrEngine_BaiduPocJNI
 * Method:    WriteAudioDataToEngine
 * Signature: ([SI)V
 */
JNIEXPORT void JNICALL Java_vr_suntec_net_vrapp_vrService_vrEngine_BaiduPocJNI_WriteAudioDataToEngine
  (JNIEnv *, jclass, jshortArray, jint);

#ifdef __cplusplus
}
#endif
#endif
