/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <memory>
/* Header for class vr_suntec_net_vrapp_vrService_vrEngine_VrEngineJNICreate */

#ifndef _Included_vr_suntec_net_vrapp_vrService_vrEngine_VrEngineJNICreate
#define _Included_vr_suntec_net_vrapp_vrService_vrEngine_VrEngineJNICreate
#ifdef __cplusplus

extern "C" {
#endif
/*
 * Class:     vr_suntec_net_vrapp_vrService_vrEngine_VrEngineJNICreate
 * Method:    CreateEngine
 * Signature: ()Z
 */

JNIEXPORT jboolean JNICALL Java_vr_suntec_net_vrapp_vrService_vrEngine_VrEngineJNICreate_CreateEngine
  (JNIEnv *, jclass);

/*
 * Class:     vr_suntec_net_vrapp_vrService_vrEngine_VrEngineJNICreate
 * Method:    DestroyEngine
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_vr_suntec_net_vrapp_vrService_vrEngine_VrEngineJNICreate_DestroyEngine
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
