/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vr_suntec_net_vrapp_vrService_vrEngine_VrEngineJNICreate_MsgCallBack */

#ifndef _Included_vr_suntec_net_vrapp_vrService_vrEngine_VrEngineJNICreate_MsgCallBack
#define _Included_vr_suntec_net_vrapp_vrService_vrEngine_VrEngineJNICreate_MsgCallBack
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
