/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_suntec_merbok_jni_vr_UIVrMessageJNI */

#ifndef _Included_net_suntec_merbok_jni_vr_UIVrMessageJNI
#define _Included_net_suntec_merbok_jni_vr_UIVrMessageJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_suntec_merbok_jni_vr_UIVrMessageJNI
 * Method:    J2CAttach
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_suntec_merbok_jni_vr_UIVrMessageJNI_J2CAttach
  (JNIEnv *, jclass);

/*
 * Class:     net_suntec_merbok_jni_vr_UIVrMessageJNI
 * Method:    J2CDetach
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_suntec_merbok_jni_vr_UIVrMessageJNI_J2CDetach
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
