#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = vr_proxy
QMAKE_CXXFLAGS += -std=c++11

SOURCES *= \
    ./JNIHelper.cpp \
    ./VoiceRecogProxy.cpp \
    ./net_suntec_merbok_jni_vr_UIVrControlJNI.cpp \
    ./net_suntec_merbok_jni_vr_UIVrMessageJNI.cpp

HEADERS *= \
    ./JNIHelper.h \
    ./VoiceRecogProxy.h \
    ./net_suntec_merbok_jni_vr_UIVrControlJNI.h \
    ./net_suntec_merbok_jni_vr_UIVrMessageJNI.h \
    ./net_suntec_merbok_jni_vr_UIVrMessageJNI_VrTriggerObserver.h

INCLUDEPATH += $$PWD/../../../../ivi/system/core/ncore
INCLUDEPATH += $$PWD/../../../../ivi/system/core
INCLUDEPATH += $$PWD/../../../../system/core/include
INCLUDEPATH += $$PWD/../../../../ivi/system/core/include
INCLUDEPATH += $$PWD/../../../../bionic/libc/include
INCLUDEPATH += $$PWD/../../../../ivi/platform/service/connectmanager/usb/handler/libnceventsys
INCLUDEPATH += $$PWD/../../../../out/target/product/merbok/obj/include
INCLUDEPATH += $$PWD/../../../../frameworks/libbase/base/commonlib/aplcommonlib/include
INCLUDEPATH += $$PWD/../../../../frameworks/libbase/base/commonlib/magiclog
INCLUDEPATH += $$PWD/../../../../frameworks/libbase/base/eventsys/include
INCLUDEPATH += $$PWD/../../../../frameworks/libbase/base/eventsys/eventcore/include
INCLUDEPATH += $$PWD/../../../../frameworks/libbase/base/eventsys/eventcore/system
INCLUDEPATH += $$PWD/../../../../frameworks/libbase/base/eventsys/NaviEventFactory/include
INCLUDEPATH += $$PWD/../../../../development/ndk/platforms/android-9/include
INCLUDEPATH += $$PWD/../../../../frameworks/libbase/base/memorytracker/include/

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

OTHER_FILES += \
    ./Android.mk \
